### ISSUE TITLE
samba36 package binary is missing

### ISSUE THREAD

**Issue by fktpa813** [zyxmon/qnapware#1]
Qnapware samba36 binary package for ARM is missing from http://qnapware.zyxmon.org/binaries-arm/. Is it possible to build the samba36 package and include it in the Qnapware repository?

I understand that it's probably not included because both QNAP and Synology include stock Samba - but I'm trying to use Qnapware on Pogoplug that doesn't have Samba.

**Comment by zyxmon** [comment]
Try this
http://qnapware.zyxmon.org/binaries-arm/test/samba36-server_3.6.24-1_qnaparm.ipk
http://qnapware.zyxmon.org/binaries-arm/test/samba36-client_3.6.24-1_qnaparm.ipk

May be some extra patches or configuration changes will be needed.

**Comment by fktpa813** [comment]
Great, thanks for super-quick response!
I don't have time today, but will try it tomorrow and let you know.

**Comment by zyxmon** [comment]
No response. Closing.
