### ISSUE TITLE
git: can't clone https repository

### ISSUE THREAD

**Issue by RichieB2B** [zyxmon/qnapware#11]
It looks like the templates are missing, or a helper, or both:

```
$ git clone https://github.com/akopytov/sysbench.git
Cloning into 'sysbench'...
warning: templates not found /Apps/opt/share/git-core/templates
fatal: Unable to find remote helper for 'https'

# opkg status git
Package: git
Version: 2.4.6-1
Depends: libc, libopenssl, libpthread, librt
Status: install user installed
Architecture: qnapx86
Installed-Time: 1454767942
```

**Comment by dynek** [comment]
You are missing package git-http

**Comment by zyxmon** [comment]
`opkg install git-http`

**Comment by RichieB2B** [comment]
Thanks, that worked. Odd choice to split that into a separate package. Never seen that before on other distros.

**Comment by 4boys** [comment]
So many things to learn. But now, one less. Thanks zymon. Saved me on a similar issue.

**Comment by zyxmon** [comment]
qnapware project was closed several years ago. Use Entware project.

**Comment by 4boys** [comment]
Your solution was used in problem I was having after installing Entware 3x. Not qnapware. Current apps, old solution still worked. for me.

So, Thanks again. Your work is appreciated very much.


On May 3, 2018 at 9:47:32 PM, zyxmon (notifications@github.com) wrote:

qnapware project was closed several years ago. Use Entware project.
