### ISSUE TITLE
perlbase-diagnostics missing perldiag.pod

### ISSUE THREAD

**Issue by bgausden** [zyxmon/qnapware#2]
When perlbase-diagnostics is installed, it should install diagnostics.pm and perldiag.pod.

It appears perldiag.pod is missing. This makes perlbase-diagnostics pretty much unusable.

`[/Apps/opt/lib/perl5/5.20/Pod] # opkg files perlbase-diagnostics
Package perlbase-diagnostics (5.20.2-1) is installed on root and has the following files:
/Apps/opt/lib/perl5/5.20/diagnostics.pm
[/Apps/opt/lib/perl5/5.20/Pod] #`

resulting in e.g.

`[/var/tmp/MySQLTuner-perl] # perl ./mysqltuner.pl
couldn't find diagnostic data in /Apps/opt/lib/perl5/5.20/pods/perldiag.pod /Apps/opt/lib/perl5/5.20 . ./mysqltuner.pl at /Apps/opt/lib/perl5/5.20/diagnostics.pm line 78, <POD_DIAG> line 523.
Compilation failed in require at ./mysqltuner.pl line 39.
BEGIN failed--compilation aborted at ./mysqltuner.pl line 39.
[/var/tmp/MySQLTuner-perl] #`

**Comment by zyxmon** [comment]
It looks like an openwert bug. Openwrt perlbase-diagnostics package does not include perldiag.pod. Can you report this bug to openwrt developers.
I'll have a look on it after I'll return from vocation.

**Comment by bgausden** [comment]
I had a look at the OpenWRT source repo and I don't see perl-5.20.2-1 only perl-5.10.0. Is the perl you're including coming from somewhere else?

The OpenWRT perl tarball [http://downloads.openwrt.org/sources/perl-5.10.0.tar.gz] _does_ include perldiag.pod.

A minor annoyance. Enjoy your break.

**Comment by bgausden** [comment]
Another thing that looks odd. The error message suggests we're searching for the pod in `/Apps/opt/lib/perl5/5.20/pods` but the installed path on my machine is `/Apps/opt/lib/perl5/5.20/Pod` (note the difference in capitalization and spelling: `pods` vs `Pod`).

**Comment by zyxmon** [comment]
The path is hardcoded in diagnostics.pm

I think it is a openwrt bug and should be fixed by openwrt developers. The next qnapware upgrade will bump perl to 5.22. May be this bug is fixed in the new upcoming version.
Closing
