### ISSUE TITLE
asterisk11-chan-iax2

### ISSUE THREAD

**Issue by the-darkvoid** [zyxmon/qnapware#3]
Entware has the package asterisk11-chan-iax2 available.

Is it possible to have this available as an armv7 package on the zyxmon repository also?

**Comment by zyxmon** [comment]
AFAIR there were errors in compiling package. I'll try to compile the new version later.

**Comment by the-darkvoid** [comment]
With the latest trunk version of both qnapware and entware-arm, asterisk11-chan-iax2 is compiling fine.
I have installed the channel module now on the Asus RT-AC87U and its functioning fine.

So you should be able to enable it for both feeds.

**Comment by zyxmon** [comment]
Thank you for testing. The next repository build will have *-chan-iax2 modules.
