### ISSUE TITLE
Python Package Missing Basic Modules

### ISSUE THREAD

**Issue by Riddles81** [zyxmon/qnapware#4]
I have installed Qnapware and installed the "python" package but it appears to be missing a key library "webbrowser.py".   I can see a reference to this file in the Package section but it's not available for use.

**Comment by zyxmon** [comment]
webbrowser.py was excluded by openwrt developpers
https://github.com/openwrt/packages/commit/c3cd9705704ae8d2d8394394f8e7dcded5cd94a7

Qnapware/Entware follow Openwrt build scripts. Please contact openwrt developers to find out - why webbrowser.py is excluded.
