### ISSUE TITLE
Binaries needed for perl List::MoreUtils

### ISSUE THREAD

**Issue by pensionado** [zyxmon/qnapware#6]
Trying to install DateTime with Perl CPAN, but runs into requirement of gcc compiler for List::MoreUtils.  Can you provide a compiled package ?

**Comment by zyxmon** [comment]
Have you installed ALL perlbase modules with:

```
opkg list | grep perlbase- | sed 's/ - .*//' | xargs opkg install
```

**Comment by pensionado** [comment]
Hi, I had installed perlbase-list, assuming it had these modules, so I 
removed complete installation and then followed your advice to install 
everything.  Then I tried again to install DateTime, actually it is 
DateTime::Local where DateTime depends on that needs List::MoreUtils, 
and it again failed due to a missing gcc compiler. So.... it appears the 
default perlbase-\* installation has no List::MoreUtils

**Comment by zyxmon** [comment]
I'll have a look on the issue, when I'm back home from vacation.

**Comment by zyxmon** [comment]
Qnapware is no longer supported. If you still this packages, please create an issue here - https://github.com/Entware-ng/Entware-ng/issues
