### ISSUE TITLE
Need binaries for Term::Readkey

### ISSUE THREAD

**Issue by pensionado** [zyxmon/qnapware#7]
Using perl -MCPAN -e shell, I get:
Can't ioctl TIOCGETP: Invalid argument  
Consider installing Term::ReadKey from CPAN site nearby
        at http://www.perl.com/CPAN
When I then try to install Term::ReadKey, it needs the compiler again.  Complete base is installed (so also perlbase-term).

**Comment by zyxmon** [comment]
Qnapware is no longer supported. If you still this packages, please create an issue here - https://github.com/Entware-ng/Entware-ng/issues
