### ISSUE TITLE
vimdiff

### ISSUE THREAD

**Issue by dynek** [zyxmon/qnapware#9]
Hello,

Any chance to see vimdiff coming into qnapware ?

Thanks for your work!

**Comment by dynek** [comment]
I checked out the sources and currently building the cross-compiling env.
I'll see if I can sort it out by myself :-)

**Comment by zyxmon** [comment]
No chance. Qnapware is closed.

Entware-ng is a new project - https://github.com/Entware-ng/Entware-ng/wiki

Please leave you request on the new project issues page after upgrading.
